testing the workflow

diff --git a/dags-to-composer.cloudbuild.yaml b/dags-to-composer.cloudbuild.yaml
--- a/dags-to-composer.cloudbuild.yaml
+++ b/dags-to-composer.cloudbuild.yaml
@@ -6,7 +6,13 @@ steps:
 
   #update the composer environment
   - name: 'gcr.io/cloud-builders/gcloud'
-    args: ['composer', 'environments', 'update', '${_COMPOSER_NAME}', '--update-pypi-packages-from-file', 'requirements-composer.txt', '--location', '${_COMPOSER_REGION}']
+    args: ['composer', 'environments', 'update', '${_COMPOSER_NAME}', '--update-pypi-packages-from-file', 'requirements-composer.txt', '--location', '${_COMPOSER_REGION}' \
+      echo "$custom_comm"; \
+        if [[ "$custom_comm" == *"ERROR: (gcloud.composer.environments.update) INVALID_ARGUMENT: No change in configuration. Must specify a change to configuration.software_configuration.pypi_dependencies"* ]]; then \
+          echo "This failure is expected if there is no change to requirements.txt"; exit 0; \ 
+        else exit 1; \
+        fi
+      ]
     id: 'update-composer-env'
 
   # run
